# Main Gunpowder Config

# Database-related stuff
database:
  # Available modes: sqlite, postgres, mysql
  mode: mysql

  # Host, unused for sqlite
  host: 192.168.35.44

  # Port, unused for sqlite
  # Default MySQL: 3306 | Default Postgres: 5432
  port: 3306

  # Name of the database
  database: qf_server_gunpowder

  # DB credentials, unused for sqlite
  # Make sure to change these!
  username: qf_admin
  password: Kjh75072@
