# Gunpowder Teleport Config

# Max number of homes per user
maxHomes: 5

# Delay between command and teleportation in seconds
teleportDelay: 5

# Seconds until /tpa expires
tpaTimeout: 120

# Distance for /rtp
rtpDistance: 10000
