# The configuration file for Shut Up Console

[shutupconsole]
# If a log message has one of these phrases, it will be filtered out from logging
phrases = ["class_2983","class_2316","class_3225","class_3231","This shouldn't happen"]

# If a log message matches one of these regex patterns, it will be filtered out from logging
regex = []
